export type Resource = {
  icon?: string;
  tags?: string[];
  id: string;
  name: string;
  category: string;
  summary: string;
  input: string;
  output: string;
  access: string;
  capabilities: string[];
  limits: string;
  url: string;
  source: string;
  checkedAt: string;
  article: string;
};
export const resources: Resource[] = [
  {
    id: "meshy",
    name: "Meshy",
    category: "3D 生成",
    summary: "将文本或图片转换成 3D 资产，提供纹理相关功能。",
    input: "文本、图片",
    output: "3D 网格、纹理",
    access: "网页 / API",
    capabilities: ["文本生成 3D", "图片生成 3D", "纹理制作"],
    limits:
      "生成后仍需按目标项目检查几何、材质与导出结果；额度和权限以实际套餐为准。",
    url: "https://www.meshy.ai/",
    source: "https://www.meshy.ai/",
    checkedAt: "2026-09-17",
    article: "image-to-3d",
  },
  {
    id: "tripo",
    name: "Tripo",
    category: "3D 生成",
    summary: "提供文本、图片到 3D 的生成流程，以及绑定相关能力。",
    input: "文本、图片",
    output: "3D 资产",
    access: "网页 / API",
    capabilities: ["文本生成 3D", "图片生成 3D", "自动绑定"],
    limits: "绑定和权重需要在项目中检查，格式支持不能代替实际导入验证。",
    url: "https://www.tripo3d.ai/",
    source: "https://www.tripo3d.ai/",
    checkedAt: "2026-09-17",
    article: "image-to-3d",
  },
  {
    id: "scenario",
    name: "Scenario",
    category: "游戏资产",
    summary: "面向创作资产制作的 AI 平台，支持风格控制与工作流。",
    input: "文本、参考素材",
    output: "创作资产",
    access: "网页 / API",
    capabilities: ["资产生成", "风格控制", "创作工作流"],
    limits:
      "具体模型、输出格式和额度需要在对应功能中确认；不是完整游戏交付服务。",
    url: "https://www.scenario.com/",
    source: "https://www.scenario.com/",
    checkedAt: "2026-09-17",
    article: "game-prototype",
  },
  {
    id: "ludo",
    name: "Ludo",
    category: "游戏资产",
    summary: "为游戏研究、概念设计和素材制作提供辅助。",
    input: "玩法目标、提示与参考",
    output: "概念和游戏素材",
    access: "网页",
    capabilities: ["玩法构思", "素材制作", "开发辅助"],
    limits: "官方说明不直接产出完整可玩游戏，仍需在引擎中实现玩法和集成资产。",
    url: "https://ludo.ai/",
    source: "https://ludo.ai/docs",
    checkedAt: "2026-09-17",
    article: "game-prototype",
  },
  {
    id: "jimeng",
    name: "即梦 AI",
    category: "视频生成",
    summary: "通过文本或图片创作视频片段。",
    input: "文本、图片",
    output: "视频片段",
    access: "网页",
    capabilities: ["文生视频", "图生视频", "镜头创作"],
    limits: "具体时长、分辨率、额度与模型权限以账号内当前规则为准。",
    url: "https://jimeng.jianying.com/",
    source: "https://jimeng.jianying.com/tools/ai-video-generator",
    checkedAt: "2026-09-17",
    article: "video-workflow",
  },
  {
    id: "runway",
    name: "Runway",
    category: "视频生成",
    summary: "通过模型与多种创作入口完成生成式视频任务。",
    input: "文本、图片等素材",
    output: "视频内容",
    access: "网页与移动应用",
    capabilities: ["视频生成", "素材创作", "工作流"],
    limits:
      "不同模型与创作入口的能力和计费不相同，参数与可用性按实际产品核验。",
    url: "https://runwayml.com/",
    source:
      "https://help.runwayml.com/hc/en-us/articles/37425232841875-Getting-Started-with-Generative-Video",
    checkedAt: "2026-09-17",
    article: "video-workflow",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "声音制作",
    summary: "通过文字描述生成音效，用于视频和游戏等作品。",
    input: "文本描述",
    output: "音效",
    access: "网页 / API",
    capabilities: ["文字生成音效", "声音素材制作"],
    limits: "具体费用按使用的产品与设置核对；同时确认素材与项目的使用条件。",
    url: "https://elevenlabs.io/",
    source:
      "https://elevenlabs.io/docs/eleven-creative/playground/sound-effects",
    checkedAt: "2026-09-17",
    article: "video-workflow",
  },
  {
    id: "blender",
    name: "Blender",
    category: "配套软件",
    summary: "用于网格编辑、UV 与素材修整的 3D 创作软件。",
    input: "3D 网格与图像素材",
    output: "编辑后的模型与场景",
    access: "桌面软件",
    capabilities: ["网格编辑", "UV 处理", "材质与场景制作"],
    limits:
      "属于配套制作软件，需掌握相应操作；生成模型的清理质量取决于实际处理。",
    url: "https://www.blender.org/",
    source: "https://www.blender.org/features/modeling/",
    checkedAt: "2026-09-16",
    article: "image-to-3d",
  },
  {
    id: "godot",
    name: "Godot",
    category: "配套软件",
    summary: "用于创建游戏工程和验证游戏玩法的引擎。",
    input: "脚本、美术和声音资产",
    output: "可运行游戏",
    access: "桌面软件",
    capabilities: ["2D 游戏制作", "场景与脚本", "游戏工程组织"],
    limits: "首个 2D 游戏官方教程假定已有基础编程经验；AI 素材仍须手动集成。",
    url: "https://godotengine.org/",
    source:
      "https://docs.godotengine.org/en/stable/getting_started/first_2d_game/index.html",
    checkedAt: "2026-09-17",
    article: "game-prototype",
  },
  {
    id: "comfyui",
    name: "ComfyUI",
    category: "图像工作流",
    summary: "使用节点组织生成模型的输入、采样与输出过程。",
    input: "模型、文本、图像与节点配置",
    output: "生成内容与可保存工作流",
    access: "本地部署 / 软件",
    capabilities: ["节点式流程", "模型工作流", "参数组织"],
    limits:
      "所需硬件与可用能力随模型变化；自定义节点和模型需独立核查来源与许可。",
    url: "https://www.comfy.org/",
    source: "https://github.com/Comfy-Org/ComfyUI",
    checkedAt: "2026-09-17",
    article: "node-workflows",
  },
  {
    id: "n8n",
    name: "n8n",
    category: "流程自动化",
    summary: "连接数据与服务，将重复工作组织成自动化流程。",
    input: "事件、数据、服务接口",
    output: "工作流执行结果",
    access: "云服务 / 自托管",
    capabilities: ["流程编排", "数据转换", "AI 相关集成"],
    limits: "使用服务接口时需要相应凭证与权限；外部操作应先用可控数据验证。",
    url: "https://n8n.io/",
    source: "https://docs.n8n.io/",
    checkedAt: "2026-09-17",
    article: "automation-basics",
  },
];
export const scenarios = [
  {
    id: "games",
    name: "游戏开发",
    summary: "从玩法原型到资产集成，逐步交付可运行的作品。",
    articles: ["game-prototype", "models-and-platforms", "reasoning-budget"],
    tools: ["ludo", "scenario", "godot", "elevenlabs"],
    steps: [
      "明确玩法与运行目标",
      "制作并验证原型",
      "准备美术和声音",
      "在引擎中集成与测试",
    ],
  },
  {
    id: "3d",
    name: "3D 建模",
    summary: "从生成网格到修整、材质和真实导入。",
    articles: ["image-to-3d", "models-and-platforms"],
    tools: ["meshy", "tripo", "blender"],
    steps: [
      "确定尺寸与资产规格",
      "生成并筛选网格",
      "修整几何和纹理",
      "在目标环境中检查",
    ],
  },
  {
    id: "video",
    name: "视频创作",
    summary: "脚本、镜头、声音与剪辑组成一条完整路线。",
    articles: ["video-workflow", "video-budget"],
    tools: ["jimeng", "runway", "elevenlabs"],
    steps: [
      "确定脚本和分镜",
      "准备参考素材",
      "逐镜生成并记录尝试",
      "配音剪辑与交付检查",
    ],
  },
  {
    id: "image",
    name: "图像工作流",
    summary: "理解节点和模型依赖，让创作过程可保存、可复用。",
    articles: ["node-workflows", "models-and-platforms"],
    tools: ["comfyui", "scenario"],
    steps: [
      "明确图像用途与规格",
      "选择模型和素材",
      "组织节点与参数",
      "检查结果与保存流程",
    ],
  },
  {
    id: "automation",
    name: "办公自动化",
    summary: "把重复的数据处理拆成有输入、有检查的流程。",
    articles: ["automation-basics", "models-and-platforms"],
    tools: ["n8n"],
    steps: [
      "描述输入与通过条件",
      "连接必要的数据来源",
      "加入校验和人工审核",
      "处理失败与重复执行",
    ],
  },
];
export const tutorialSlugs = [
  "game-prototype",
  "image-to-3d",
  "video-workflow",
  "node-workflows",
  "automation-basics",
];
